-- begin CARGOLOAD_CARGO_BAY
alter table CARGOLOAD_CARGO_BAY add constraint FK_CARGOLOAD_CARGO_BAY_SHIP foreign key (SHIP_ID) references CARGOLOAD_SHIP(ID)^
create unique index IDX_CARGOLOAD_CARGO_BAY_UNIQ_BAY_NUMBER on CARGOLOAD_CARGO_BAY (BAY_NUMBER) ^
create index IDX_CARGOLOAD_CARGO_BAY_SHIP on CARGOLOAD_CARGO_BAY (SHIP_ID)^
-- end CARGOLOAD_CARGO_BAY
