-- begin CARGOLOAD_CARGO_BAY
alter table CARGOLOAD_CARGO_BAY add constraint FK_CARGOLOAD_CARGO_BAY_SHIP foreign key (SHIP_ID) references CARGOLOAD_SHIP(ID)^
create unique index IDX_CARGOLOAD_CARGO_BAY_UNIQ_BAY_NUMBER on CARGOLOAD_CARGO_BAY (BAY_NUMBER) ^
create index IDX_CARGOLOAD_CARGO_BAY_SHIP on CARGOLOAD_CARGO_BAY (SHIP_ID)^
-- end CARGOLOAD_CARGO_BAY
-- begin CARGOLOAD_CARGO_SKU
alter table CARGOLOAD_CARGO_SKU add constraint FK_CARGOLOAD_CARGO_SKU_PRODUCT foreign key (PRODUCT_ID) references CARGOLOAD_PRODUCT(ID)^
create index IDX_CARGOLOAD_CARGO_SKU_PRODUCT on CARGOLOAD_CARGO_SKU (PRODUCT_ID)^
-- end CARGOLOAD_CARGO_SKU

-- begin CARGOLOAD_CARGO_ITEM_POSITION
alter table CARGOLOAD_CARGO_ITEM_POSITION add constraint FK_CARGOLOAD_CARGO_ITEM_POSITION_SKU foreign key (SKU_ID) references CARGOLOAD_CARGO_SKU(ID)^
alter table CARGOLOAD_CARGO_ITEM_POSITION add constraint FK_CARGOLOAD_CARGO_ITEM_POSITION_BAY foreign key (BAY_ID) references CARGOLOAD_CARGO_BAY(ID)^
alter table CARGOLOAD_CARGO_ITEM_POSITION add constraint FK_CARGOLOAD_CARGO_ITEM_POSITION_SHIP_LOADING_SCHEME foreign key (SHIP_LOADING_SCHEME_ID) references CARGOLOAD_SHIP_LOADING_SCHEME(ID)^
create index IDX_CARGOLOAD_CARGO_ITEM_POSITION_SKU on CARGOLOAD_CARGO_ITEM_POSITION (SKU_ID)^
create index IDX_CARGOLOAD_CARGO_ITEM_POSITION_BAY on CARGOLOAD_CARGO_ITEM_POSITION (BAY_ID)^
create index IDX_CARGOLOAD_CARGO_ITEM_POSITION_SHIP_LOADING_SCHEME on CARGOLOAD_CARGO_ITEM_POSITION (SHIP_LOADING_SCHEME_ID)^
-- end CARGOLOAD_CARGO_ITEM_POSITION
