-- begin CARGOLOAD_CARGO_BAY
alter table CARGOLOAD_CARGO_BAY add constraint FK_CARGOLOAD_CARGO_BAY_SHIP foreign key (SHIP_ID) references CARGOLOAD_SHIP(ID)^
create unique index IDX_CARGOLOAD_CARGO_BAY_UNIQ_BAY_NUMBER on CARGOLOAD_CARGO_BAY (BAY_NUMBER) ^
create index IDX_CARGOLOAD_CARGO_BAY_SHIP on CARGOLOAD_CARGO_BAY (SHIP_ID)^
-- end CARGOLOAD_CARGO_BAY
-- begin CARGOLOAD_CARGO_SKU
alter table CARGOLOAD_CARGO_SKU add constraint FK_CARGOLOAD_CARGO_SKU_PRODUCT foreign key (PRODUCT_ID) references CARGOLOAD_PRODUCT(ID)^
create index IDX_CARGOLOAD_CARGO_SKU_PRODUCT on CARGOLOAD_CARGO_SKU (PRODUCT_ID)^
-- end CARGOLOAD_CARGO_SKU
-- begin CARGOLOAD_CARGO_LOADING_SCHEME
alter table CARGOLOAD_CARGO_LOADING_SCHEME add constraint FK_CARGOLOAD_CARGO_LOADING_SCHEME_SKU foreign key (SKU_ID) references CARGOLOAD_CARGO_SKU(ID)^
alter table CARGOLOAD_CARGO_LOADING_SCHEME add constraint FK_CARGOLOAD_CARGO_LOADING_SCHEME_BAY foreign key (BAY_ID) references CARGOLOAD_CARGO_BAY(ID)^
create index IDX_CARGOLOAD_CARGO_LOADING_SCHEME_SKU on CARGOLOAD_CARGO_LOADING_SCHEME (SKU_ID)^
create index IDX_CARGOLOAD_CARGO_LOADING_SCHEME_BAY on CARGOLOAD_CARGO_LOADING_SCHEME (BAY_ID)^
-- end CARGOLOAD_CARGO_LOADING_SCHEME
