alter table CARGOLOAD_CARGO_LOADING_SCHEME add constraint FK_CARGOLOAD_CARGO_LOADING_SCHEME_SKU foreign key (SKU_ID) references CARGOLOAD_CARGO_SKU(ID);
alter table CARGOLOAD_CARGO_LOADING_SCHEME add constraint FK_CARGOLOAD_CARGO_LOADING_SCHEME_BAY foreign key (BAY_ID) references CARGOLOAD_CARGO_BAY(ID);
create index IDX_CARGOLOAD_CARGO_LOADING_SCHEME_SKU on CARGOLOAD_CARGO_LOADING_SCHEME (SKU_ID);
create index IDX_CARGOLOAD_CARGO_LOADING_SCHEME_BAY on CARGOLOAD_CARGO_LOADING_SCHEME (BAY_ID);
