alter table CARGOLOAD_CARGO_SKU add constraint FK_CARGOLOAD_CARGO_SKU_PRODUCT foreign key (PRODUCT_ID) references CARGOLOAD_PRODUCT(ID);
create index IDX_CARGOLOAD_CARGO_SKU_PRODUCT on CARGOLOAD_CARGO_SKU (PRODUCT_ID);
