alter table CARGOLOAD_CARGO_BAY add constraint FK_CARGOLOAD_CARGO_BAY_SHIP foreign key (SHIP_ID) references CARGOLOAD_SHIP(ID);
create index IDX_CARGOLOAD_CARGO_BAY_SHIP on CARGOLOAD_CARGO_BAY (SHIP_ID);
